import { useState, useEffect } from 'react';
import { Loader2, Download, CheckCircle, AlertTriangle, FileText } from 'lucide-react';
import api from '../api/client';

/* eslint-disable @typescript-eslint/no-explicit-any */

interface AuditData {
  generated_at: string;
  report_period: string;
  summary: {
    total_findings: number;
    resolved: number;
    open: number;
    critical_open: number;
    high_open: number;
    remediation_rate_pct: number;
    avg_remediation_hrs: number;
    median_remediation_hrs: number;
    compliance_score: number;
  };
  by_severity: Record<string, { total: number; resolved: number; open: number }>;
  monthly_trend: { month: string; opened: number; resolved: number; net: number }[];
  findings: {
    id: number;
    github_id: number;
    number: number;
    title: string;
    severity: string;
    status: string;
    created_at: string;
    resolved_at: string;
    remediation_hrs: number | null;
    pr_url: string | null;
    repo: string;
  }[];
}

const severityOrder: Record<string, number> = { critical: 0, high: 1, medium: 2, low: 3 };
const severityColor: Record<string, string> = {
  critical: '#e53e3e', high: '#e53e3e', medium: '#d97706', low: '#718096',
};

export default function AuditReport() {
  const [data, setData] = useState<AuditData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    (async () => {
      try {
        const report = await api.getAuditReport();
        setData(report);
      } catch (e) {
        console.error('Audit report error:', e);
      } finally {
        setLoading(false);
      }
    })();
  }, []);

  const exportPdf = () => {
    if (!data) return;
    // Generate a printable HTML and trigger print dialog
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const severities = Object.entries(data.by_severity)
      .sort((a, b) => (severityOrder[a[0]] ?? 9) - (severityOrder[b[0]] ?? 9));

    const findingsHtml = data.findings.map(f => `
      <tr>
        <td style="padding:6px 10px;border-bottom:1px solid #eee;font-family:monospace;font-size:11px">#${f.number || f.github_id}</td>
        <td style="padding:6px 10px;border-bottom:1px solid #eee;font-size:12px">${f.title}</td>
        <td style="padding:6px 10px;border-bottom:1px solid #eee;text-transform:capitalize;color:${severityColor[f.severity] || '#666'};font-weight:700;font-size:11px">${f.severity}</td>
        <td style="padding:6px 10px;border-bottom:1px solid #eee;text-transform:capitalize;font-size:11px;color:${f.status === 'resolved' ? '#0d7c5f' : '#666'}">${f.status}</td>
        <td style="padding:6px 10px;border-bottom:1px solid #eee;font-family:monospace;font-size:11px">${f.remediation_hrs ? f.remediation_hrs + 'h' : '\u2014'}</td>
      </tr>
    `).join('');

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head><title>Backlog Zero - Security Audit Report</title>
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 40px; color: #1a1a1a; }
        h1 { font-size: 24px; margin-bottom: 4px; }
        h2 { font-size: 16px; margin-top: 28px; border-bottom: 2px solid #3969CA; padding-bottom: 6px; color: #3969CA; }
        .meta { font-size: 12px; color: #666; margin-bottom: 24px; }
        .grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin: 16px 0; }
        .card { border: 1px solid #e5e7eb; border-radius: 8px; padding: 14px; text-align: center; }
        .card-value { font-size: 28px; font-weight: 900; }
        .card-label { font-size: 10px; text-transform: uppercase; letter-spacing: 0.08em; color: #999; margin-top: 4px; }
        table { width: 100%; border-collapse: collapse; font-size: 12px; }
        th { text-align: left; padding: 8px 10px; background: #f7f7f7; border-bottom: 2px solid #ddd; font-size: 10px; text-transform: uppercase; letter-spacing: 0.08em; color: #666; }
        .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #ddd; font-size: 11px; color: #999; text-align: center; }
        @media print { body { margin: 20px; } }
      </style></head>
      <body>
        <h1>Security Audit Report</h1>
        <div class="meta">Generated by Backlog Zero &mdash; ${data.report_period}</div>

        <h2>Executive Summary</h2>
        <div class="grid">
          <div class="card"><div class="card-value" style="color:#3969CA">${data.summary.compliance_score}%</div><div class="card-label">Compliance Score</div></div>
          <div class="card"><div class="card-value" style="color:#0d7c5f">${data.summary.remediation_rate_pct}%</div><div class="card-label">Remediation Rate</div></div>
          <div class="card"><div class="card-value" style="color:#0d7c5f">${data.summary.avg_remediation_hrs}h</div><div class="card-label">Avg Remediation Time</div></div>
          <div class="card"><div class="card-value" style="color:${data.summary.critical_open > 0 ? '#e53e3e' : '#0d7c5f'}">${data.summary.critical_open}</div><div class="card-label">Critical Open</div></div>
        </div>

        <h2>Severity Breakdown</h2>
        <table>
          <tr><th>Severity</th><th>Total</th><th>Resolved</th><th>Open</th><th>Rate</th></tr>
          ${severities.map(([sev, d]) => `
            <tr>
              <td style="padding:6px 10px;border-bottom:1px solid #eee;text-transform:capitalize;font-weight:700;color:${severityColor[sev] || '#666'}">${sev}</td>
              <td style="padding:6px 10px;border-bottom:1px solid #eee">${d.total}</td>
              <td style="padding:6px 10px;border-bottom:1px solid #eee;color:#0d7c5f">${d.resolved}</td>
              <td style="padding:6px 10px;border-bottom:1px solid #eee;color:${d.open > 0 ? '#e53e3e' : '#0d7c5f'}">${d.open}</td>
              <td style="padding:6px 10px;border-bottom:1px solid #eee">${d.total > 0 ? Math.round((d.resolved / d.total) * 100) : 0}%</td>
            </tr>
          `).join('')}
        </table>

        <h2>All Findings (${data.findings.length})</h2>
        <table>
          <tr><th>ID</th><th>Issue</th><th>Severity</th><th>Status</th><th>Remediation</th></tr>
          ${findingsHtml}
        </table>

        <div class="footer">
          Backlog Zero &mdash; AI-Powered Security Operations &mdash; Generated ${new Date(data.generated_at).toLocaleString()}
        </div>
      </body>
      </html>
    `);
    printWindow.document.close();
    setTimeout(() => printWindow.print(), 500);
  };

  if (loading) {
    return (
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '60vh' }}>
        <Loader2 size={32} style={{ color: 'var(--blue)' }} className="animate-spin" />
      </div>
    );
  }

  if (!data) {
    return (
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '60vh', color: 'var(--dim)' }}>
        Failed to load audit report. Check your backend connection.
      </div>
    );
  }

  const s = data.summary;
  const severities = Object.entries(data.by_severity)
    .sort((a, b) => (severityOrder[a[0]] ?? 9) - (severityOrder[b[0]] ?? 9));

  return (
    <div className="animate-fade-in">
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 20 }}>
        <div>
          <div style={{ fontSize: 13, fontWeight: 700, color: 'var(--ink)', display: 'flex', alignItems: 'center', gap: 8 }}>
            <FileText size={15} /> Security Audit Report
          </div>
          <div style={{ fontSize: 11, color: 'var(--dim)', marginTop: 2 }}>{data.report_period}</div>
        </div>
        <button onClick={exportPdf} style={{
          fontSize: 12, fontWeight: 600, padding: '8px 16px', borderRadius: 8,
          border: 'none', background: 'var(--purple)', color: '#fff',
          cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 6,
        }}>
          <Download size={14} /> Export PDF
        </button>
      </div>

      {/* Summary Cards */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 12, marginBottom: 24 }}>
        <div style={{ background: 'var(--white)', border: '1px solid var(--rule)', borderRadius: 11, padding: '16px', textAlign: 'center', position: 'relative', overflow: 'hidden' }}>
          <div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: 3, background: 'var(--purple)' }} />
          <div style={{ fontSize: 36, fontWeight: 900, color: 'var(--purple)', letterSpacing: '-.04em' }}>{s.compliance_score}%</div>
          <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: '.08em', color: 'var(--dim)', marginTop: 4 }}>COMPLIANCE SCORE</div>
        </div>
        <div style={{ background: 'var(--white)', border: '1px solid var(--rule)', borderRadius: 11, padding: '16px', textAlign: 'center', position: 'relative', overflow: 'hidden' }}>
          <div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: 3, background: 'var(--green)' }} />
          <div style={{ fontSize: 36, fontWeight: 900, color: 'var(--green)', letterSpacing: '-.04em' }}>{s.remediation_rate_pct}%</div>
          <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: '.08em', color: 'var(--dim)', marginTop: 4 }}>REMEDIATION RATE</div>
        </div>
        <div style={{ background: 'var(--white)', border: '1px solid var(--rule)', borderRadius: 11, padding: '16px', textAlign: 'center', position: 'relative', overflow: 'hidden' }}>
          <div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: 3, background: 'var(--green)' }} />
          <div style={{ fontSize: 36, fontWeight: 900, color: 'var(--green)', letterSpacing: '-.04em' }}>{s.avg_remediation_hrs}h</div>
          <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: '.08em', color: 'var(--dim)', marginTop: 4 }}>AVG REMEDIATION</div>
          <div style={{ fontSize: 10, color: 'var(--dim)', marginTop: 2 }}>median: {s.median_remediation_hrs}h</div>
        </div>
        <div style={{ background: 'var(--white)', border: '1px solid var(--rule)', borderRadius: 11, padding: '16px', textAlign: 'center', position: 'relative', overflow: 'hidden' }}>
          <div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: 3, background: s.critical_open > 0 ? '#e53e3e' : 'var(--green)' }} />
          <div style={{ fontSize: 36, fontWeight: 900, color: s.critical_open > 0 ? '#e53e3e' : 'var(--green)', letterSpacing: '-.04em' }}>{s.open}</div>
          <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: '.08em', color: 'var(--dim)', marginTop: 4 }}>OPEN FINDINGS</div>
          <div style={{ fontSize: 10, color: 'var(--dim)', marginTop: 2 }}>{s.critical_open} critical, {s.high_open} high</div>
        </div>
      </div>

      {/* Severity Breakdown */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, marginBottom: 24 }}>
        <div style={{ background: 'var(--white)', border: '1px solid var(--rule)', borderRadius: 12, overflow: 'hidden' }}>
          <div style={{ padding: '12px 16px', borderBottom: '1px solid var(--rule)', fontSize: 12, fontWeight: 700, color: 'var(--ink)' }}>
            Severity Breakdown
          </div>
          {severities.map(([sev, d]) => (
            <div key={sev} style={{ display: 'grid', gridTemplateColumns: '80px 1fr 60px 60px', padding: '10px 16px', borderBottom: '1px solid var(--rule)', alignItems: 'center', gap: 10 }}>
              <div style={{ fontSize: 12, fontWeight: 700, textTransform: 'capitalize', color: severityColor[sev] || 'var(--dim)' }}>{sev}</div>
              <div style={{ height: 6, borderRadius: 3, background: 'var(--bg2)', overflow: 'hidden' }}>
                <div style={{ height: '100%', borderRadius: 3, background: severityColor[sev] || 'var(--dim)', width: d.total > 0 ? `${(d.resolved / d.total) * 100}%` : '0%', transition: 'width 0.8s ease' }} />
              </div>
              <div style={{ fontSize: 11, fontFamily: 'var(--mono)', fontWeight: 700, color: 'var(--green)', textAlign: 'right' }}>{d.resolved}/{d.total}</div>
              <div style={{ fontSize: 11, fontFamily: 'var(--mono)', fontWeight: 600, color: 'var(--dim)', textAlign: 'right' }}>
                {d.total > 0 ? Math.round((d.resolved / d.total) * 100) : 0}%
              </div>
            </div>
          ))}
        </div>

        {/* Monthly Trend */}
        <div style={{ background: 'var(--white)', border: '1px solid var(--rule)', borderRadius: 12, overflow: 'hidden' }}>
          <div style={{ padding: '12px 16px', borderBottom: '1px solid var(--rule)', fontSize: 12, fontWeight: 700, color: 'var(--ink)' }}>
            Monthly Trend
          </div>
          {data.monthly_trend.map(m => (
            <div key={m.month} style={{ display: 'grid', gridTemplateColumns: '120px 1fr 1fr 80px', padding: '12px 16px', borderBottom: '1px solid var(--rule)', alignItems: 'center' }}>
              <div style={{ fontSize: 12, fontWeight: 600, color: 'var(--ink)' }}>{m.month}</div>
              <div style={{ fontSize: 11, color: '#d97706', fontWeight: 600 }}>+{m.opened} opened</div>
              <div style={{ fontSize: 11, color: 'var(--green)', fontWeight: 600 }}>{m.resolved} resolved</div>
              <div style={{ fontSize: 11, fontFamily: 'var(--mono)', fontWeight: 700, textAlign: 'right', color: m.net <= 0 ? 'var(--green)' : '#e53e3e' }}>
                {m.net <= 0 ? '\u2193' : '\u2191'} {Math.abs(m.net)}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Findings Table */}
      <div style={{ background: 'var(--white)', border: '1px solid var(--rule)', borderRadius: 12, overflow: 'hidden', marginBottom: 24 }}>
        <div style={{ padding: '12px 16px', borderBottom: '1px solid var(--rule)', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <div style={{ fontSize: 12, fontWeight: 700, color: 'var(--ink)' }}>All Findings ({data.findings.length})</div>
          <div style={{ display: 'flex', gap: 8 }}>
            <span style={{ fontSize: 10, fontWeight: 600, padding: '2px 8px', borderRadius: 10, background: 'rgba(33,193,154,.1)', color: 'var(--green)' }}>
              <CheckCircle size={10} style={{ marginRight: 3, verticalAlign: 'middle' }} />{s.resolved} resolved
            </span>
            {s.open > 0 && (
              <span style={{ fontSize: 10, fontWeight: 600, padding: '2px 8px', borderRadius: 10, background: 'rgba(229,62,62,.1)', color: '#e53e3e' }}>
                <AlertTriangle size={10} style={{ marginRight: 3, verticalAlign: 'middle' }} />{s.open} open
              </span>
            )}
          </div>
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: '80px 1fr 80px 80px 80px', padding: '8px 16px', background: 'var(--bg)', borderBottom: '1px solid var(--rule)' }}>
          {['ID', 'Issue', 'Severity', 'Status', 'Time'].map(h => (
            <div key={h} style={{ fontSize: 10, fontWeight: 700, letterSpacing: '.08em', textTransform: 'uppercase' as any, color: 'var(--dim)' }}>{h}</div>
          ))}
        </div>
        {data.findings.slice(0, 20).map(f => (
          <div key={f.id} style={{ display: 'grid', gridTemplateColumns: '80px 1fr 80px 80px 80px', padding: '10px 16px', borderBottom: '1px solid var(--rule)', alignItems: 'center' }}>
            <div style={{ fontFamily: 'var(--mono)', fontSize: 11, fontWeight: 600, color: 'var(--purple)' }}>#{f.number || f.github_id}</div>
            <div style={{ fontSize: 12, color: 'var(--ink)', fontWeight: 500, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', paddingRight: 10 }}>
              {f.title.replace(/^\[SECURITY\]\s*/i, '')}
            </div>
            <div>
              <span style={{ fontSize: 9, fontWeight: 700, padding: '2px 6px', borderRadius: 8, textTransform: 'capitalize', background: severityColor[f.severity] ? severityColor[f.severity] + '18' : 'var(--bg2)', color: severityColor[f.severity] || 'var(--dim)' }}>
                {f.severity}
              </span>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
              {f.status === 'resolved' ? (
                <><span style={{ width: 6, height: 6, borderRadius: '50%', background: 'var(--green)', display: 'inline-block' }} /><span style={{ fontSize: 11, color: 'var(--green)', fontWeight: 600 }}>Resolved</span></>
              ) : (
                <><span style={{ width: 6, height: 6, borderRadius: '50%', background: 'var(--dim)', display: 'inline-block' }} /><span style={{ fontSize: 11, color: 'var(--dim)', fontWeight: 600, textTransform: 'capitalize' }}>{f.status}</span></>
              )}
            </div>
            <div style={{ fontFamily: 'var(--mono)', fontSize: 11, color: f.remediation_hrs ? 'var(--green)' : 'var(--dim)', fontWeight: 600 }}>
              {f.remediation_hrs ? f.remediation_hrs + 'h' : '\u2014'}
            </div>
          </div>
        ))}
        {data.findings.length > 20 && (
          <div style={{ padding: '12px 16px', textAlign: 'center', fontSize: 11, color: 'var(--dim)' }}>
            + {data.findings.length - 20} more findings {'\u2014'} Export PDF for full list
          </div>
        )}
      </div>
    </div>
  );
}
